### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mattbrailsford** [Kirill19837/umContentCreator#10]
What's the license of this repository?

**Comment by Kirill19837** [comment]
Hello Matt. I prefer to make all source code available for the community, so it is probably the same as the Umbraco CMS sources. what do you advice?

**Comment by mattbrailsford** [comment]
Hey @Kirill19837 

yea, licensing can be a “fun” challenge. If you really don’t mind what anyone does with your code, MIT is usually an easy option and is what Umbraco uses, but it is worth reading up a little to see if there is one that aligns closer to your values.

**Comment by Kirill19837** [comment]
I think https://licenses.nuget.org/MIT is fine for this case. I updated the readme. We plan to invest some time to support it and add some functionality. If you have any thoughts, please message me.
